-- Categorías y marcas
INSERT INTO CATEGORY(NAME) VALUES ('Smartphones');
INSERT INTO CATEGORY(NAME) VALUES ('Laptops');
INSERT INTO CATEGORY(NAME) VALUES ('Accesorios');

INSERT INTO BRAND(NAME) VALUES ('Samsung');
INSERT INTO BRAND(NAME) VALUES ('Xiaomi');
INSERT INTO BRAND(NAME) VALUES ('Motorola');
INSERT INTO BRAND(NAME) VALUES ('HP');

-- Productos
INSERT INTO PRODUCT(NAME, SKU, PRICE, STOCK, CATEGORY_ID, BRAND_ID)
SELECT 'Galaxy A35', 'SAM-A35', 1099.90, 15,
       (SELECT ID FROM CATEGORY WHERE NAME='Smartphones'),
       (SELECT ID FROM BRAND WHERE NAME='Samsung')
FROM DUAL;

INSERT INTO PRODUCT(NAME, SKU, PRICE, STOCK, CATEGORY_ID, BRAND_ID)
SELECT 'Redmi Note 13', 'XIA-RN13', 899.50, 20,
       (SELECT ID FROM CATEGORY WHERE NAME='Smartphones'),
       (SELECT ID FROM BRAND WHERE NAME='Xiaomi')
FROM DUAL;

INSERT INTO PRODUCT(NAME, SKU, PRICE, STOCK, CATEGORY_ID, BRAND_ID)
SELECT 'HP 245 G9', 'HP-245G9', 1999.00, 8,
       (SELECT ID FROM CATEGORY WHERE NAME='Laptops'),
       (SELECT ID FROM BRAND WHERE NAME='HP')
FROM DUAL;

-- Clientes
INSERT INTO CUSTOMER(FULL_NAME, EMAIL, PHONE) VALUES ('Juan Pérez', 'juan@demo.com', '999111222');
INSERT INTO CUSTOMER(FULL_NAME, EMAIL, PHONE) VALUES ('Ana López', 'ana@demo.com',  '988777666');

-- Ventas de ejemplo (para Dashboard)
INSERT INTO SALE_ORDER (ORDER_DATE, CUSTOMER_ID, TOTAL)
SELECT SYSTIMESTAMP, (SELECT ID FROM CUSTOMER WHERE EMAIL='juan@demo.com'), 0 FROM DUAL;

INSERT INTO ORDER_ITEM (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
SELECT (SELECT MAX(ID) FROM SALE_ORDER),
       (SELECT ID FROM PRODUCT WHERE SKU='SAM-A35'), 2, 1099.90 FROM DUAL;

INSERT INTO ORDER_ITEM (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
SELECT (SELECT MAX(ID) FROM SALE_ORDER),
       (SELECT ID FROM PRODUCT WHERE SKU='XIA-RN13'), 1, 899.50 FROM DUAL;

-- Recalcular total
UPDATE SALE_ORDER so
SET TOTAL = (SELECT NVL(SUM(oi.QUANTITY * oi.UNIT_PRICE),0) FROM ORDER_ITEM oi WHERE oi.ORDER_ID=so.ID);
COMMIT;
